#!/usr/bin/env bash

./stop || true
./build docker || exit 1

echo "### Starting tickle-repo-introspect service docker ###"

tickle_repo_introspect_service_port=${TICKLE_REPO_INTROSPECT_SERVICE_PORT:-8080}
docker run --rm --name tickle-repo-introspect -d \
    -e JAVA_MAX_HEAP_SIZE=2G \
    -e INSTANCE=devel \
    -e TICKLE_REPO_URL=${TICKLE_REPO_URL} \
    -p ${tickle_repo_introspect_service_port}:8080 \
    docker-io.dbc.dk/tickle-repo-introspect:devel

attempts=0
max_attempts=60
until $(curl --output /dev/null --silent --head --fail http://localhost:${tickle_repo_introspect_service_port}/api/status); do
    if [[ ${attempts} -eq ${max_attempts} ]]; then
        break
    fi

    printf '.'
    attempts=$(($attempts+1))
    sleep 0.5
done

echo ""
echo "### Status for tickle-repo-introspect service ###"
curl -vs http://localhost:${tickle_repo_introspect_service_port}/api/status
echo ""